// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'andev-us';
}

<mat-toolbar color="primary" class="header">
  <mat-toolbar-row>
    <a routerLink="/"><h1><mat-icon>person</mat-icon> an<span class="dev">dev</span></h1></a>
    <nav class="tabs">
      <a mat-button routerLink="/videos" routerLinkActive="active">Videos</a>
      <a mat-button routerLink="/articles" routerLinkActive="active">Articles</a>
      <a mat-button routerLink="/speaking" routerLinkActive="active">Speaking</a>
      <a mat-button routerLink="/teaching" routerLinkActive="active">Teaching</a>
      <a mat-button routerLink="/links" routerLinkActive="active">Links</a>
    </nav>
    <nav class="links">
      <a mat-button href="http://www.github.com/adwiens">GitHub</a>
    </nav>
  </mat-toolbar-row>
</mat-toolbar>

<div class="content">
  <div class="badge">
    <img src="assets/images/me.PNG">
    <span>
      My name is Andrew Wiens.
      Software Developer at <a href="http://www.oasisdigital.com/">Oasis Digital</a>.
      <a href="http://www.angularbootcamp.com/">Angular Boot Camp</a> instructor.
      CS graduate student.
    </span>
  </div>
  <router-outlet></router-outlet>
</div>

<mat-toolbar class="footer">
  <mat-toolbar-row>
    <nav>
      <a mat-button href="http://www.github.com/adwiens">GitHub</a>
      <a mat-button href="http://www.stackblitz.com/@adwiens">StackBlitz</a>
      <a mat-button href="https://scholar.google.com/citations?user=_N2X7KwAAAAJ">Google Scholar</a>
      <a mat-button href="http://www.twitter.com/adwiens">Twitter</a>
      <a mat-button href="https://www.linkedin.com/in/andrew-wiens-59859038/">LinkedIn</a>
    </nav>
    <span class="small">Powered by Angular Universal</span>
  </mat-toolbar-row>
</mat-toolbar>

// react/src/App.js
import React from 'react';
import './App.scss';
import TopBar from './TopBar';
import { BrowserRouter, Route, Redirect } from 'react-router-dom';
import Cards from './Cards';
import Badge from './Badge';
import { Toolbar, ToolbarRow } from '@rmwc/toolbar';
import '@material/toolbar/dist/mdc.toolbar.css';
import { videos, articles, speaking } from './posts.js';
import { Button } from '@rmwc/button';
import '@rmwc/button/styles';

export default function App() {
  return (
    <BrowserRouter>
      <TopBar />
      <div className="app-main">
        <Badge />
        <Route path="/" exact={true}>
          <Redirect to="/videos" />
        </Route>
        <Route path="/videos">
          <Cards posts={videos} />
        </Route>
        <Route path="/articles">
          <Cards posts={articles} />
        </Route>
        <Route path="/speaking">
          <Cards posts={speaking} />
        </Route>
      </div>
      <Toolbar>
        <ToolbarRow className="footer">
          <nav>
            <Button tag="a" href="http://www.github.com/adwiens">GitHub</Button>
            <Button tag="a" href="http://www.stackblitz.com/@adwiens">StackBlitz</Button>
            <Button tag="a" href="https://scholar.google.com/citations?user=_N2X7KwAAAAJ">Google Scholar</Button>
            <Button tag="a" href="http://www.twitter.com/adwiens">Twitter</Button>
            <Button tag="a" href="https://www.linkedin.com/in/drew-wiens-59859038/">LinkedIn</Button>
          </nav>
          <span class="small">Powered by React and Express</span>
        </ToolbarRow>
      </Toolbar>
    </BrowserRouter>
  );
}
